### ISSUE TITLE
Use GitHub code highlighting in the README.md file

### ISSUE THREAD

**Issue by Naereen** [lindig/ocaml-style#3]
Hi,
This is easy to fix and will greatly help reading this document.
Instead of using 4-space indented snippets, like

    (* first snippet with 4 spaces indentation, no color *)
    let this = example ();;

it would look better to use backticks snippets, like
```ocaml
(* second snippet with ```ocaml .... ```, and pretty colors! *)
let this = example ();;
```

**Comment by Naereen** [comment]
@lindig If you agree on the change, I can take time to fill a PR or let you do it, as you prefer.

**Comment by lindig** [comment]
The one problem with this is that it does not work (IMHO) with the discount(1) implementation of Markdown that I use to generate the HTML, which includes a table of contents. See the Makefile. I'm generally happy to add syntax colouring, though.

**Comment by lindig** [comment]
An alternative would be to hand-craft a table of contents and to get rid of the HTML generation. However, is there good support for links within Markdown?

**Comment by Naereen** [comment]
Yes perfect support, see [for example this guide](https://guides.github.com/features/mastering-markdown/)

**Comment by lindig** [comment]
I've now embedded a TOC like you suggested. So the road to backtick-quoted code with syntax colouring is free.

**Comment by Naereen** [comment]
Great!

**Comment by Naereen** [comment]
Can you do it?

**Comment by lindig** [comment]
Sure. But it will have to wait until tomorrow.

**Comment by Naereen** [comment]
Same here, good night 🛌 !

**Comment by lindig** [comment]
This is done with bc715db.

**Comment by Naereen** [comment]
Looks good ✨ !
