### ISSUE TITLE
Add a Table of Contents for the README.md version?

### ISSUE THREAD

**Issue by Naereen** [lindig/ocaml-style#4]
It's great to have this README.html version, but I guess most people will just read the document directly on GitHub.

It's quite easy to add a table of contents in the README.md file (and generate it automatically). See for instance a tool like https://github.com/ekalinin/github-markdown-toc.

A bonus can be to enclose the whole table of content between HTML `<details>...</details>` tag, so it is collapsed by default.
(See on [this project](https://github.com/Naereen/badges#list-of-badges-in-markdown) for an example)

**Comment by lindig** [comment]
That's cool. I'd be happy to move into this direction and to give up HTML generation. I only introduced it for offline reading and for the TOC.

**Comment by lindig** [comment]
I'm looking at this Go program to create a TOC: https://github.com/ekalinin/github-markdown-toc.go.

**Comment by Naereen** [comment]
Honestly I didn't understand the reason of the HTML version: it's doesn't seem to be hosted anywhere, there is no link given to it etc.
I would advise to just use a simple Markdown README.md file and let GitHub's pretty in-browser markdown-to-html do the magic ✨ :octocat: !

And then if you want a HTML version, you can enable GitHub pages and have it rendered automatically on, e.g., https://lindig.github.io/ocaml-style/

**Comment by lindig** [comment]
The HTML is gone. I'd like to think this issue is resolved.

**Comment by Naereen** [comment]
It does look good!
