### ISSUE TITLE
line length is 80, not 100

### ISSUE THREAD

**Issue by UnixJunkie** [lindig/ocaml-style#6]

**Comment by lindig** [comment]
I'm happy to include an argument for 80 characters but you need to provide it.

**Comment by UnixJunkie** [comment]
Cf. official INRIA guidelines:
The page is 80 columns wide.

    Justification: This width makes it possible to read the code on all displays and to print it in a legible font on a standard sheet.

Justification two: it allows to read several pages of program at once on one screen, side by side.

**Comment by lindig** [comment]
I have added 6a6e125

**Comment by UnixJunkie** [comment]
perfect!
